### ISSUE TITLE
Any chance you have time to tag a new release?

### ISSUE THREAD

**Issue by rromanchuk** [emcniece/docker-boarding#3]
So I can continue being lazy 😬 

It's currently broken with https://github.com/fastlane/boarding/issues/186

**Comment by emcniece** [comment]
Yep, taking a look now.

**Comment by emcniece** [comment]
I really wish there were more releases on https://github.com/fastlane/boarding/releases to sync with. I'll bump local to `0.0.2` but this detached versioning bugs me. Any ideas for more relevant tagging?

**Comment by emcniece** [comment]
@rromanchuk pushed `emcniece/docker-boarding:0.0.2`. Have a test, maybe [review the PR](https://github.com/emcniece/docker-boarding/pull/4), let me know if everything works and close this at will.
